### ISSUE TITLE
Cannot create new direct message

### ISSUE THREAD

**Issue by lenny-horstink** [crusttech/webapp-messaging#13]
I tried to create a new direct message, but hitting the create button does not do anything.

1) Enter latest
2) Hit the (+) next to direct messages
3) Select the users Lee Fisher and Lenny Horstink
  -> When I add "Lee Fisher" I get the error "TypeError: "e is null" " in the inspector
4) Hit create
  -> nothing happens (although in the inspector it seems like the channel is created)

Browser: Firefox

![screenshot from 2019-03-05 08-28-57](https://user-images.githubusercontent.com/44468809/53788178-54c24800-3f21-11e9-938d-4a111f4ac4cc.png)

**Comment by lenny-horstink** [comment]
In Chrome:

![screenshot from 2019-03-05 08-41-57](https://user-images.githubusercontent.com/44468809/53788605-999aae80-3f22-11e9-888c-83d3df23fc8d.png)

**Comment by lenny-horstink** [comment]
When I created a direct message to a group of people with my account, and not the dummy account, it worked

**Comment by darh** [comment]
Was fixed.
