### ISSUE TITLE
Provide an ability to open channel list on mobile-view

### ISSUE THREAD

**Issue by darh** [crusttech/webapp-messaging#26]
When a channel is opened we show channel header with a link/button to chan-panel in the top-left corner.

In case we (somehow) navigate away from the channel view (for example, after #20, by closing channel form) we can not open channel panel back.

Make sure the chan-panel is always opened in mobile if we land on welcome screen (or anything else).

**Comment by tjerman** [comment]
Will fix. In the mean time, you are still able to open/close it using gestures.
