### ISSUE TITLE
Landing screen for mobile user of messaging webapp

### ISSUE THREAD

**Issue by darh** [crusttech/webapp-messaging#29]
Provide a dedicated page (`/mobile`) that shows:
 - link for mobile app auto-configuration (see #28)
 - link to `play.google.com` when available
 - link to `app store` when available

We will force this page for all mobile visits to webapp when everything is in place (working flow, apps published).

**Comment by Fajfa** [comment]
Merged: https://github.com/crusttech/webapp-messaging/commit/dd2f89b69707d820abd39c77c020157a13dcc144

**Comment by zmija** [comment]
https://github.com/cortezaproject/corteza-webapp-messaging/issues/53
