### ISSUE TITLE
Tagging channels/users when editing a message doesn't open the suggestion box

### ISSUE THREAD

**Issue by tjerman** [crusttech/webapp-messaging#34]
![Screenshot from 2019-04-02 12-49-17](https://user-images.githubusercontent.com/12545711/55397202-fbf8c600-5545-11e9-9a58-a1f3bf48a54f.png)

**Comment by zmija** [comment]
@tjerman nice catch, will you tackle this one or Jože?

**Comment by zmija** [comment]
@Fajfa assigning it to you for now, if you can't find a solution let me know

**Comment by Fajfa** [comment]
Merged to master
commit: https://github.com/crusttech/webapp-messaging/commit/d6899180acb35f5f922cf143099953b59b898f80

**Comment by Fajfa** [comment]
Merged: https://github.com/crusttech/webapp-messaging/commit/1fc7e140e386ad23ce05277957a2790934feeaf7
