### ISSUE TITLE
Search results > show in channel option doesn't work

### ISSUE THREAD

**Issue by zmija** [crusttech/webapp-messaging#35]
When I search along the channels I see the option to 'jump' to the selected message inside the belonging channel. When I click on that option I'm redirected to the right channel, but not to the right message. 

If that's too complicated I think it's perfectly fine if we open it as the thread.

**Comment by Fajfa** [comment]
Go to message now opens the channel and the desired message in a thread panel.

**Comment by darh** [comment]
@Fajfa can you link commit here as well. ty

**Comment by Fajfa** [comment]
Pushed to develop: https://github.com/cortezaproject/corteza-webapp-messaging/commit/bcf436f61ec345c96460310abcea203ba89a6f61

**Comment by zmija** [comment]
I will close it for now as it does jump to the selected message. BUT the rest of the chat history is missing... see the screenshot. Low priority so no action required for now.


Full chat:
![image](https://user-images.githubusercontent.com/8327569/77054578-3e721780-69d0-11ea-8109-1a90f0b8a80d.png)

Go to the search result:
![image](https://user-images.githubusercontent.com/8327569/77054645-4fbb2400-69d0-11ea-944a-fbad50aaa26f.png)
