### ISSUE TITLE
Deleting a message 

### ISSUE THREAD

**Issue by zmija** [crusttech/webapp-messaging#80]
**Describe the bug**
Bug when trying to delete my own messages, inconsistent behavior between main messaging and thread messaging

**To Reproduce**
1. Go to https://feature-migrate-tiptap.test.cortezaproject.org/ as a non-admin user
2. Insert a text to the main chat
3. Insert a text to the thread
4. Try to delete your own message in a thread
5. You'll get a ```messaging.service.NoPermissions```in the error console and the message won't delete
6. Go back to the main chat and try to delete a message there > message will delete

**Expected behavior**
- permission set should reflect on both - main message screen and inside thread
- If I don't have permissions to delete my own messages, I shouldn't be able to see that option in the context menu
- If I have a permission to delete my own messages, I should be able to do so in both - main 

The same applies to "Edit message" so check if there's the same situation. behavior should be the same as stated above.

**Comment by zmija** [comment]
I just realized I'm actually an administrator so that's even weirder now...

**Comment by tjerman** [comment]
Fixed with https://github.com/cortezaproject/corteza-server/commit/3c68b3b770f73f19b8a0ec90bc8bf98c2c712ad3
